title: Actividades sobre el piano
description: Directorio de actividades sobre el piano
theme: jekyll-theme-tactile
# theme: jekyll-theme-cayman
# O prueba con:
# theme: jekyll-theme-modernist
# theme: jekyll-theme-tactile

collections:
  activities:
    output: true
    permalink: /:path/
plugins:
  - jekyll-relative-links
